dist: xenial
language: java
git:
  depth: false
install: true
script:
  - mvn install
after_success:
  - cd $TRAVIS_BUILD_DIR
  - bash check-jar.sh $PROJECT_NAME
before_cache:
  - cd $TRAVIS_BUILD_DIR
  - bash clean-cache.sh
cache:
  directories:
  - $HOME/.m2